// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrkslgyjtzqtboxfdyco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhya3NsZ3lqdHpxdGJveGZkeWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTI3MDMsImV4cCI6MjA3MzY2ODcwM30.JacVVi8E2csfVNMNtU6NLWeGDJj-SZbjoJOOKmJ-d54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});